name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
# 拉取master分支
      - name: Checkout
        uses: actions/checkout@master
      # 设置qemu来编译多个平台的镜像
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 登陆dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 编译并且推送到dockerhub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64, linux/arm64

          tags: |
            abcdelf/vits_rtts:latest
            abcdelf/vits_rtts:0.1
